In [44]:
import pandas as pd

In [45]:
arboles= pd.read_csv("https://raw.githubusercontent.com/MumukiProject/datasets/master/arbolado-publico-lineal.csv")
arboles

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
0,-58.389059,-34.620026,Árbol,2430.0,7.0,20.0,17.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1609.0,0.0
1,-58.389211,-34.620034,Árbol,2431.0,8.0,33.0,16.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1617.0,0.0
2,-58.389269,-34.620037,Árbol,2432.0,2.0,3.0,0.0,9.0,Oleáceas,Ligustrum,Ligustrum lucidum,Ligustro,Árbol Latifoliado Perenne,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1629.0,0.0
3,-58.389525,-34.620052,Árbol,2433.0,9.0,17.0,0.0,7.0,Aceráceas,Acer,Acer negundo,Arce negundo,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",0.0,0.0
4,-58.389608,-34.620057,Árbol,2434.0,6.0,13.0,14.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1655.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372689,-58.493294,-34.623746,Árbol,938000239.0,10.0,52.0,5.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1328.0,0.0
372690,-58.493241,-34.623788,Árbol,938000240.0,11.0,60.0,10.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1320.0,0.0
372691,-58.493176,-34.623840,Árbol,938000241.0,10.0,56.0,20.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1312.0,0.0
372692,-58.493116,-34.623887,Árbol,938000242.0,10.0,58.0,0.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,0.0,0.0
372693,-58.493086,-34.624042,Árbol,938000243.0,3.0,5.0,0.0,8.0,Litráceas,Lagerstroemia,Lagerstroemia indica,Crespón (Àrbol de Júpiter),Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,"Diaz, Cesar, Gral.",0.0,0.0

In [46]:
arboles["height"].max()

60.0

In [47]:
arboles["height"].median()

8.0

In [48]:
arboles["diameter"].mean()

31.94135134990099

In [49]:
arboles["diameter"].quantile(0.75)

43.0

In [50]:
arboles.describe()

,long,lat,tree_id,height,diameter,inclination,species_id,comuna,num1,num2
count,372659.000000,372659.000000,3.726940e+05,372694.000000,372694.000000,372686.000000,372694.000000,372694.000000,372635.000000,372605.000000
mean,-58.458556,-34.613312,2.710744e+07,8.473085,31.941351,3.069834,38.703695,9.124542,1895.047352,40.598980
std,0.041818,0.034253,4.134081e+07,4.576827,20.207274,6.029981,141.187865,3.866489,1917.173186,386.231441
min,-58.530413,-34.702639,2.430000e+03,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,-58.491353,-34.639264,1.661592e+05,5.000000,17.000000,0.000000,1.000000,6.000000,0.000000,0.000000
50%,-58.465525,-34.615744,1.700314e+07,8.000000,28.000000,0.000000,3.000000,10.000000,1449.000000,0.000000
75%,-58.428724,-34.586780,3.810204e+07,11.000000,43.000000,5.000000,10.000000,12.000000,3181.000000,0.000000
max,-58.342784,-34.534262,9.380002e+08,60.000000,426.000000,60.000000,999.000000,15.000000,16392.000000,14038.000000

In [51]:
arboles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372694 entries, 0 to 372693
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   long           372659 non-null  float64
 1   lat            372659 non-null  float64
 2   site_type      372694 non-null  object
 3   tree_id        372694 non-null  float64
 4   height         372694 non-null  float64
 5   diameter       372694 non-null  float64
 6   inclination    372686 non-null  float64
 7   species_id     372694 non-null  float64
 8   fam_name       372694 non-null  object
 9   gen_name       372694 non-null  object
 10  sci_name       372694 non-null  object
 11  comm_name      372694 non-null  object
 12  fol_type       372694 non-null  object
 13  origin         372694 non-null  object
 14  man_code       372694 non-null  object
 15  neighbourhood  372694 non-null  object
 16  comuna         372694 non-null  float64
 17  street         372682 non-null  object
 18  num1           372635 non-null  float64
 19  num2           372605 non-null  float64
dtypes: float64(10), object(10)
memory usage: 56.9+ MB

In [52]:
arboles["height"] >= 7

0          True
1          True
2         False
3          True
4         False
          ...
372689     True
372690     True
372691     True
372692     True
372693    False
Name: height, Length: 372694, dtype: bool

Leccion 4: ejercicio 2

In [53]:
arboles_de_palermo = arboles[arboles["neighbourhood"] == "PALERMO"]
arboles_de_palermo

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
95041,-58.437231,-34.584817,Árbol,168390.0,7.0,41.0,35.0,7.0,Aceráceas,Acer,Acer negundo,Arce negundo,Árbol Latifoliado Caducifolio,Exótico,35-017,PALERMO,14.0,Gorriti,0.0,0.0
95042,-58.437276,-34.584783,Árbol,168391.0,15.0,43.0,0.0,18.0,Moráceas,Ficus,Ficus elastica,Gomero,Árbol Latifoliado Perenne,Exótico,35-017,PALERMO,14.0,Gorriti,5605.0,0.0
95043,-58.437416,-34.584678,Árbol,168392.0,3.0,13.0,7.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,35-017,PALERMO,14.0,Gorriti,5625.0,0.0
95044,-58.437468,-34.584640,Árbol,168393.0,5.0,16.0,19.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,35-017,PALERMO,14.0,Gorriti,0.0,0.0
95045,-58.437551,-34.584578,Árbol,168394.0,7.0,17.0,10.0,80.0,Meliáceas,Cedrela,Cedrela fissilis,Cedro misionero (Cedro colorado o Cedro real),Árbol Conífero Caducifolio,Nativo/Autóctono,35-017,PALERMO,14.0,Gorriti,5641.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370835,-58.430834,-34.592673,Árbol,219004408.0,14.0,40.0,3.0,17.0,Simarrubáceas,Ailanthus,Ailanthus altissima,Árbol del cielo (Ailanto o Árbol de los dioses),Árbol Latifoliado Caducifolio,Exótico,31-105,PALERMO,14.0,"Vega, Niceto, Cnel.",4738.0,0.0
370836,-58.430746,-34.592731,Árbol,219004409.0,7.0,25.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,31-105,PALERMO,14.0,"Vega, Niceto, Cnel.",4726.0,0.0
370837,-58.430677,-34.592778,Árbol,219004410.0,7.0,24.0,3.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,31-105,PALERMO,14.0,"Vega, Niceto, Cnel.",4714.0,0.0
370838,-58.430608,-34.592825,Árbol,219004411.0,9.0,34.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,31-105,PALERMO,14.0,"Vega, Niceto, Cnel.",4712.0,0.0
370839,-58.430531,-34.592876,Árbol,219004412.0,7.0,22.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,31-105,PALERMO,14.0,"Vega, Niceto, Cnel.",0.0,0.0

Leccion 4: Ejercicio 3

In [54]:
sauces= arboles[arboles["comm_name"].str.startswith("Sauce")]
sauces

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
654,-58.401518,-34.594771,Árbol,3202.0,24.0,70.0,0.0,32.0,Salicáceas,Salix,Salix x erythroflexuosa,Sauce eléctrico,Árbol Latifoliado Caducifolio,Exótico,11-004,RECOLETA,2.0,Santa Fe Av.,2432.0,0.0
1233,-58.398963,-34.597287,Árbol,3849.0,9.0,32.0,0.0,32.0,Salicáceas,Salix,Salix x erythroflexuosa,Sauce eléctrico,Árbol Latifoliado Caducifolio,Exótico,11-031,RECOLETA,2.0,"Uriburu Jose E., Pres.",0.0,0.0
1286,-58.399023,-34.595214,Árbol,3907.0,21.0,63.0,24.0,234.0,Salicáceas,Salix,Salix humboldtiana,Sauce criollo,Árbol Latifoliado Caducifolio,Nativo/Autóctono,11-033,RECOLETA,2.0,Santa Fe Av.,0.0,0.0
1294,-58.399703,-34.594786,Árbol,3916.0,9.0,24.0,0.0,32.0,Salicáceas,Salix,Salix x erythroflexuosa,Sauce eléctrico,Árbol Latifoliado Caducifolio,Exótico,11-033,RECOLETA,2.0,Azcuenaga,1135.0,0.0
2140,-58.393885,-34.597293,Árbol,4916.0,7.0,23.0,0.0,32.0,Salicáceas,Salix,Salix x erythroflexuosa,Sauce eléctrico,Árbol Latifoliado Caducifolio,Exótico,11-075,RECOLETA,2.0,"Alvear, Marcelo T. De",1840.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371317,-58.427520,-34.649188,Árbol,219004895.0,6.0,16.0,9.0,234.0,Salicáceas,Salix,Salix humboldtiana,Sauce criollo,Árbol Latifoliado Caducifolio,Nativo/Autóctono,46-169B,NUEVA POMPEYA,4.0,"Arbeletche, Anibal P.",0.0,0.0
371710,-58.408170,-34.645448,Árbol,219005288.0,12.0,56.0,5.0,234.0,Salicáceas,Salix,Salix humboldtiana,Sauce criollo,Árbol Latifoliado Caducifolio,Nativo/Autóctono,32-066,PARQUE PATRICIOS,4.0,Elia,0.0,0.0
372282,-58.374756,-34.652102,Árbol,219005860.0,11.0,53.0,0.0,367.0,Salicáceas,Salix,Salix sp.,Sauce,No Determinado,No Determinado,18-106,BARRACAS,4.0,"Cruz, Osvaldo Av.",2026.0,0.0
372283,-58.374683,-34.652081,Árbol,219005861.0,11.0,54.0,4.0,367.0,Salicáceas,Salix,Salix sp.,Sauce,No Determinado,No Determinado,18-106,BARRACAS,4.0,"Cruz, Osvaldo Av.",2020.0,0.0
372596,-58.507724,-34.604768,Árbol,904001509.0,7.0,27.0,0.0,107.0,Salicáceas,Salix,Salix babylonica,Sauce llorón,Árbol Latifoliado Caducifolio,Exótico,81-051,VILLA DEVOTO,11.0,"Varela, Jose Pedro",0.0,0.0

Leccion 4: ejercicio 4

In [55]:
arboles[(arboles["comuna"] == 10) & arboles["fam_name"].str.startswith("Oleáceas")]

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
66356,-58.474736,-34.636657,Árbol,131732.0,4.0,18.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,54-179,FLORESTA,10.0,"Bonifacio, Jose",3487.0,0.0
66357,-58.474679,-34.636636,Árbol,131733.0,6.0,30.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,54-179,FLORESTA,10.0,"Bonifacio, Jose",3487.0,0.0
66358,-58.474621,-34.636615,Árbol,131734.0,7.0,26.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,54-179,FLORESTA,10.0,"Bonifacio, Jose",3477.0,0.0
66360,-58.474280,-34.636492,Árbol,131736.0,3.0,12.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,54-179,FLORESTA,10.0,"Bonifacio, Jose",3425.0,0.0
66361,-58.474209,-34.636466,Árbol,131737.0,3.0,14.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,54-179,FLORESTA,10.0,"Bonifacio, Jose",3415.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372675,-58.493316,-34.624010,Árbol,938000225.0,10.0,22.0,10.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,El Araucano,1395.0,0.0
372677,-58.494081,-34.623261,Árbol,938000227.0,8.0,28.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,"Magariños Cervantes, A.",4308.0,0.0
372678,-58.493912,-34.623256,Árbol,938000228.0,11.0,50.0,5.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,0.0,0.0
372679,-58.493869,-34.623289,Árbol,938000229.0,5.0,8.0,5.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1382.0,0.0
372682,-58.493657,-34.623458,Árbol,938000232.0,14.0,48.0,18.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1364.0,0.0

Leccion 4: ejercicio 5

In [56]:
arboles[(arboles["neighbourhood"] == "Balvanera") | arboles["comuna"] == 10]

Empty DataFrame
Columns: [long, lat, site_type, tree_id, height, diameter, inclination, species_id, fam_name, gen_name, sci_name, comm_name, fol_type, origin, man_code, neighbourhood, comuna, street, num1, num2]
Index: []

Leccion 4: ejercicio 6

In [57]:
arboles[
     (arboles["neighbourhood"] == "FLORESTA") 
     | (arboles["neighbourhood"] == "RECOLETA") 
     | (arboles["neighbourhood"] == "BELGRANO")
     | (arboles["neighbourhood"] == "NUÑEZ")]

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
515,-58.389869,-34.598446,Árbol,3037.0,2.0,4.0,0.0,6.0,Moráceas,Ficus,Ficus benjamina,Ficus,Árbol Latifoliado Perenne,Exótico,07-016,RECOLETA,2.0,Paraguay,0.0,0.0
516,-58.390172,-34.598468,Árbol,3038.0,3.0,5.0,0.0,11.0,Bignoniáceas,Jacarandá,Jacarandá mimosifolia,Jacarandá,Árbol Latifoliado Caducifolio,Nativo/Autóctono,07-016,RECOLETA,2.0,Paraguay,1623.0,0.0
517,-58.390232,-34.598472,Árbol,3039.0,40.0,5.0,0.0,11.0,Bignoniáceas,Jacarandá,Jacarandá mimosifolia,Jacarandá,Árbol Latifoliado Caducifolio,Nativo/Autóctono,07-016,RECOLETA,2.0,Paraguay,1625.0,0.0
518,-58.390322,-34.598478,Árbol,3040.0,40.0,4.0,0.0,11.0,Bignoniáceas,Jacarandá,Jacarandá mimosifolia,Jacarandá,Árbol Latifoliado Caducifolio,Nativo/Autóctono,07-016,RECOLETA,2.0,Paraguay,1637.0,0.0
519,-58.389784,-34.598304,Árbol,3044.0,7.0,11.0,0.0,17.0,Simarrubáceas,Ailanthus,Ailanthus altissima,Árbol del cielo (Ailanto o Árbol de los dioses),Árbol Latifoliado Caducifolio,Exótico,07-016,RECOLETA,2.0,Montevideo,990.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372689,-58.493294,-34.623746,Árbol,938000239.0,10.0,52.0,5.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1328.0,0.0
372690,-58.493241,-34.623788,Árbol,938000240.0,11.0,60.0,10.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1320.0,0.0
372691,-58.493176,-34.623840,Árbol,938000241.0,10.0,56.0,20.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1312.0,0.0
372692,-58.493116,-34.623887,Árbol,938000242.0,10.0,58.0,0.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,0.0,0.0
372693,-58.493086,-34.624042,Árbol,938000243.0,3.0,5.0,0.0,8.0,Litráceas,Lagerstroemia,Lagerstroemia indica,Crespón (Àrbol de Júpiter),Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,"Diaz, Cesar, Gral.",0.0,0.0

In [58]:
arboles[arboles["neighbourhood"].isin(["FLORESTA", "RECOLETA", "BELGRANO", "NUÑEZ"])]

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
515,-58.389869,-34.598446,Árbol,3037.0,2.0,4.0,0.0,6.0,Moráceas,Ficus,Ficus benjamina,Ficus,Árbol Latifoliado Perenne,Exótico,07-016,RECOLETA,2.0,Paraguay,0.0,0.0
516,-58.390172,-34.598468,Árbol,3038.0,3.0,5.0,0.0,11.0,Bignoniáceas,Jacarandá,Jacarandá mimosifolia,Jacarandá,Árbol Latifoliado Caducifolio,Nativo/Autóctono,07-016,RECOLETA,2.0,Paraguay,1623.0,0.0
517,-58.390232,-34.598472,Árbol,3039.0,40.0,5.0,0.0,11.0,Bignoniáceas,Jacarandá,Jacarandá mimosifolia,Jacarandá,Árbol Latifoliado Caducifolio,Nativo/Autóctono,07-016,RECOLETA,2.0,Paraguay,1625.0,0.0
518,-58.390322,-34.598478,Árbol,3040.0,40.0,4.0,0.0,11.0,Bignoniáceas,Jacarandá,Jacarandá mimosifolia,Jacarandá,Árbol Latifoliado Caducifolio,Nativo/Autóctono,07-016,RECOLETA,2.0,Paraguay,1637.0,0.0
519,-58.389784,-34.598304,Árbol,3044.0,7.0,11.0,0.0,17.0,Simarrubáceas,Ailanthus,Ailanthus altissima,Árbol del cielo (Ailanto o Árbol de los dioses),Árbol Latifoliado Caducifolio,Exótico,07-016,RECOLETA,2.0,Montevideo,990.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372689,-58.493294,-34.623746,Árbol,938000239.0,10.0,52.0,5.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1328.0,0.0
372690,-58.493241,-34.623788,Árbol,938000240.0,11.0,60.0,10.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1320.0,0.0
372691,-58.493176,-34.623840,Árbol,938000241.0,10.0,56.0,20.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1312.0,0.0
372692,-58.493116,-34.623887,Árbol,938000242.0,10.0,58.0,0.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,0.0,0.0
372693,-58.493086,-34.624042,Árbol,938000243.0,3.0,5.0,0.0,8.0,Litráceas,Lagerstroemia,Lagerstroemia indica,Crespón (Àrbol de Júpiter),Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,"Diaz, Cesar, Gral.",0.0,0.0

Leccion 4: ejercicio 7

In [59]:
arboles[~arboles["comm_name"].str.startswith("Fresno")]

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
2,-58.389269,-34.620037,Árbol,2432.0,2.0,3.0,0.0,9.0,Oleáceas,Ligustrum,Ligustrum lucidum,Ligustro,Árbol Latifoliado Perenne,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1629.0,0.0
3,-58.389525,-34.620052,Árbol,2433.0,9.0,17.0,0.0,7.0,Aceráceas,Acer,Acer negundo,Arce negundo,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",0.0,0.0
5,-58.389665,-34.620060,Árbol,2435.0,3.0,2.0,0.0,28.0,Rosáceas,Prunus,Prunus cerasifera,Ciruelo de jardín,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1661.0,0.0
10,-58.390168,-34.619941,Árbol,2441.0,7.0,27.0,0.0,6.0,Moráceas,Ficus,Ficus benjamina,Ficus,Árbol Latifoliado Perenne,Exótico,14-017,CONSTITUCION,1.0,Solis,994.0,0.0
34,-58.388962,-34.619363,Árbol,2467.0,11.0,18.0,0.0,4.0,Tiliaceas,Tilia,Tilia viridis subsp. x moltkei,Tilo,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Cevallos, Virrey",0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372689,-58.493294,-34.623746,Árbol,938000239.0,10.0,52.0,5.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1328.0,0.0
372690,-58.493241,-34.623788,Árbol,938000240.0,11.0,60.0,10.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1320.0,0.0
372691,-58.493176,-34.623840,Árbol,938000241.0,10.0,56.0,20.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1312.0,0.0
372692,-58.493116,-34.623887,Árbol,938000242.0,10.0,58.0,0.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,0.0,0.0
372693,-58.493086,-34.624042,Árbol,938000243.0,3.0,5.0,0.0,8.0,Litráceas,Lagerstroemia,Lagerstroemia indica,Crespón (Àrbol de Júpiter),Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,"Diaz, Cesar, Gral.",0.0,0.0

Leccion 4: ejercicio 8

In [60]:
arboles[arboles["street"].isna()]

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
13667,-58.399585,-34.602789,Árbol,18300.0,4.0,7.0,0.0,5.0,Oleáceas,Ligustrum,Ligustrum lucidum for. aureo-variegatum,Ligustro disciplinado (Ligustro variegado),Árbol Latifoliado Perenne,Exótico,09-047,BALVANERA,3.0,NaN,547.0,0.0
30148,-58.395248,-34.626713,Árbol,68384.0,10.0,50.0,10.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,22-039,SAN CRISTOBAL,3.0,NaN,2179.0,0.0
58994,-58.443560,-34.615603,Árbol,123412.0,3.0,12.0,7.0,6.0,Moráceas,Ficus,Ficus benjamina,Ficus,Árbol Latifoliado Perenne,Exótico,45-019,CABALLITO,6.0,NaN,454.0,0.0
81182,-58.473926,-34.564482,Árbol,150590.0,11.0,50.0,11.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,41-002,COGHLAN,12.0,NaN,2656.0,0.0
84159,-58.463787,-34.627756,Árbol,154078.0,11.0,26.0,10.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,65-072A,FLORES,7.0,NaN,2441.0,0.0
160395,-58.494237,-34.612140,Árbol,12000808.0,10.0,20.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,81-079A,VILLA DEL PARQUE,11.0,NaN,0.0,0.0
186154,-58.454284,-34.567895,Árbol,17002947.0,6.0,9.0,0.0,43.0,Leguminosas,Bauhinia,Bauhinia forticata,Pata de vaca (Pezuña de vaca),Árbol Latifoliado Caducifolio,Nativo/Autóctono,37-135,COLEGIALES,13.0,NaN,0.0,0.0
218616,-58.488071,-34.651757,Árbol,26103081.0,9.0,30.0,15.0,331.0,Leguminosas,Acacia,Acacia sp.,Acacia,No Determinado,No Determinado,62-131,MATADEROS,9.0,NaN,0.0,0.0
241669,-58.488008,-34.617925,Árbol,31001312.0,12.0,57.0,0.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,79-107,VILLA SANTA RITA,11.0,NaN,1509.0,0.0
270084,-58.463276,-34.611764,Árbol,35001504.0,6.0,11.0,18.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,59-036,VILLA GRAL. MITRE,11.0,NaN,1873.0,0.0
277992,-58.487785,-34.605276,Árbol,38000673.0,18.0,63.0,0.0,2.0,Platanaceae,Platanus,Platanus x acerifolia,Plátano,Árbol Latifoliado Caducifolio,Exótico,69-018,VILLA DEL PARQUE,11.0,NaN,2968.0,0.0
308884,-58.402492,-34.639113,Árbol,45004386.0,2.0,3.0,0.0,8.0,Litráceas,Lagerstroemia,Lagerstroemia indica,Crespón (Àrbol de Júpiter),Árbol Latifoliado Caducifolio,Exótico,24-023,PARQUE PATRICIOS,4.0,NaN,0.0,0.0

Leccion 4: ejercicio 9

In [61]:
len(arboles[arboles["num1"].notna ()])

372635

Leccion 4: ejercicio 10

In [62]:
arboles.dropna(inplace=True)

Leccion 4: ejercicio 11

In [63]:
arboles.dropna(subset=["long","lat"])

,long,lat,site_type,tree_id,height,diameter,inclination,species_id,fam_name,gen_name,sci_name,comm_name,fol_type,origin,man_code,neighbourhood,comuna,street,num1,num2
0,-58.389059,-34.620026,Árbol,2430.0,7.0,20.0,17.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1609.0,0.0
1,-58.389211,-34.620034,Árbol,2431.0,8.0,33.0,16.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1617.0,0.0
2,-58.389269,-34.620037,Árbol,2432.0,2.0,3.0,0.0,9.0,Oleáceas,Ligustrum,Ligustrum lucidum,Ligustro,Árbol Latifoliado Perenne,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1629.0,0.0
3,-58.389525,-34.620052,Árbol,2433.0,9.0,17.0,0.0,7.0,Aceráceas,Acer,Acer negundo,Arce negundo,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",0.0,0.0
4,-58.389608,-34.620057,Árbol,2434.0,6.0,13.0,14.0,1.0,Oleáceas,Fraxinus,Fraxinus pennsylvanica,Fresno americano,Árbol Latifoliado Caducifolio,Exótico,14-017,CONSTITUCION,1.0,"Calvo, Carlos",1655.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372689,-58.493294,-34.623746,Árbol,938000239.0,10.0,52.0,5.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1328.0,0.0
372690,-58.493241,-34.623788,Árbol,938000240.0,11.0,60.0,10.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1320.0,0.0
372691,-58.493176,-34.623840,Árbol,938000241.0,10.0,56.0,20.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,1312.0,0.0
372692,-58.493116,-34.623887,Árbol,938000242.0,10.0,58.0,0.0,3.0,Meliáceas,Melia,Melia azeradach,Paraíso,Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,Sanabria,0.0,0.0
372693,-58.493086,-34.624042,Árbol,938000243.0,3.0,5.0,0.0,8.0,Litráceas,Lagerstroemia,Lagerstroemia indica,Crespón (Àrbol de Júpiter),Árbol Latifoliado Caducifolio,Exótico,79-005A,FLORESTA,10.0,"Diaz, Cesar, Gral.",0.0,0.0

Leccion 4: ejercicio 12

In [64]:
arboles["inclination"].fillna(arboles["inclination"].mean(), inplace=True)

Leccion 4: ejercicio 13        arboles(arboles["diameter"].quantile(0.98)) % (arboles["diameter"] <= )

Leccion 5: ejercicio 4

In [1]:
import pandas as pd
cruceros_originales = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRSa9oM9fC-QlT7VOeGhZQtrWnlNSTsk3U8DWGTOXUWtPH6u9o5O5eZ0kTg8mFTwAn9vMdGRK7o2SPB/pub?gid=751983160&single=true&output=csv")
cruceros = cruceros_originales.copy()

In [2]:
cruceros.head()

,cruise_id,country_id,country,date,date_id,port_id,port,total_people,visits_amount,total_expenses,tours_expenses,feed_expenses,transport_expenses,shopping_expenses,other_expenses
0,41,57,Suiza,2016-12-02,13485,1,Montevideo,6,0,0.0,0.0,0.00,0.0,0.00,0.0
1,42,59,Otro de Europa,2016-12-02,13485,1,Montevideo,4,0,200.0,100.0,40.00,40.0,20.00,0.0
2,43,41,Canada,2016-12-02,13485,1,Montevideo,4,0,100.0,100.0,0.00,0.0,0.00,0.0
3,44,32,Colombia,2016-12-02,13485,1,Montevideo,3,0,600.0,0.0,300.00,0.0,300.00,0.0
4,45,70,EE.UU.,2016-12-02,13485,1,Montevideo,2,0,200.0,0.0,98.36,0.0,101.64,0.0

In [4]:
cruceros["country"]

0                 Suiza
1        Otro de Europa
2                Canada
3              Colombia
4                EE.UU.
              ...
12011         Argentina
12012         Argentina
12013         Argentina
12014         Argentina
12015         Argentina
Name: country, Length: 12016, dtype: object

In [5]:
cruceros["region"] = cruceros["country"].map({
    "Uruguay": "Nacional",
    "Argentina": "Regional",
    "Brasil": "Regional"})

cruceros["region"]

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
           ...
12011    Regional
12012    Regional
12013    Regional
12014    Regional
12015    Regional
Name: region, Length: 12016, dtype: object

In [7]:
cruceros["region"].fillna("No regional")

0        No regional
1        No regional
2        No regional
3        No regional
4        No regional
            ...
12011       Regional
12012       Regional
12013       Regional
12014       Regional
12015       Regional
Name: region, Length: 12016, dtype: object

In [8]:
cruceros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12016 entries, 0 to 12015
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cruise_id           12016 non-null  int64
 1   country_id          12016 non-null  int64
 2   country             12016 non-null  object
 3   date                12016 non-null  object
 4   date_id             12016 non-null  int64
 5   port_id             12016 non-null  int64
 6   port                12016 non-null  object
 7   total_people        12016 non-null  int64
 8   visits_amount       12016 non-null  int64
 9   total_expenses      12016 non-null  float64
 10  tours_expenses      12016 non-null  float64
 11  feed_expenses       12016 non-null  float64
 12  transport_expenses  12016 non-null  float64
 13  shopping_expenses   12016 non-null  float64
 14  other_expenses      12016 non-null  float64
 15  region              8262 non-null   object
dtypes: float64(6), int64(6), object(4)
memory usage: 1.5+ MB

In [12]:
cruceros["region", "visits_amount"]

KeyError: ('region', 'visits_amount')

In [1]:
import pandas as pd

In [2]:
producto = ["Shampoo sólido","Crema de manos"]

stock = [5,6]

precio = [300, 600]

indices = [1, 2]

productos = {"Producto": producto, "Stock": stock, "Precio unitario": precio}

df = pd.DataFrame(data=productos, index=indices)
df

         Producto  Stock  Precio unitario
1  Shampoo sólido      5              300
2  Crema de manos      6              600

In [3]:
print(df.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Producto</th>
      <th>Stock</th>
      <th>Precio unitario</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>Shampoo sólido</td>
      <td>5</td>
      <td>300</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Crema de manos</td>
      <td>6</td>
      <td>600</td>
    </tr>
  </tbody>
</table>